# Generated by Django 5.2.1 on 2025-06-22 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='default.jpg', help_text="Main filename in store/gallery/, e.g. 'crocs_front.jpg'", max_length=255),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FilePathField(blank=True, help_text='Select a file from store/static/store/gallery/', match='.*\\.(jpg|jpeg|png|gif)$', path='C:\\Users\\farah\\OneDrive\\Desktop\\shoes\\walkease\\store\\static\\store\\gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
    ]
