# Generated by Django 5.2.1 on 2025-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
