# Generated by Django 5.2.1 on 2025-06-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_force_add_slug_to_category'),
        ('store', '0004_force_alter_product_description'),
    ]

    operations = [
    ]
