# Generated by Django 5.2.1 on 2025-06-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_create_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
