# Generated by Django 5.2.1 on 2025-06-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
